### ISSUE TITLE
RNG Variable problem

### ISSUE THREAD

**Issue by 157946a** [Kqliber/Expansion-RNG#5]
[23:04:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.9.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.12.2.jar:git-Paper-1574]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[Paper-1.12.2.jar:git-Paper-1574]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1479) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1284) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.12.2.jar:git-Paper-1574]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2.jar:git-Paper-1574]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2.jar:git-Paper-1574]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: me/kaliber/rngExpansion/libs/jvm/internal/Intrinsics
        at me.kaliber.expansions.rng.RNGExpansion.onRequest(RNGExpansion.kt) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:205) ~[?:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:186) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.12.2.jar:git-Paper-1574]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: me.kaliber.rngExpansion.libs.jvm.internal.Intrinsics
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at me.kaliber.expansions.rng.RNGExpansion.onRequest(RNGExpansion.kt) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:205) ~[?:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:186) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.12.2.jar:git-Paper-1574]
        ... 15 more

The above is an error. No matter I put it on the lore of the menu or the command test of papi, the above error will be reported. It cannot be used normally. Both variables cannot be used. The papi version is 2.9.2 and the extended version is 1.3.

**Comment by Kqliber** [comment]
I can reproduce this is on 2.9.2, but it works fine on the latest version. Please update PlaceholderAPI as you are almost 3 years out of date

**Comment by 157946a** [comment]
There is nothing wrong with the update, but the new version of papi has problems with luckperms, and the time variable is inaccurate. I told the luckperms author that he didn't care, so I closed my feedback directly.

**Comment by 157946a** [comment]
[17:48:38 ERROR]: [PlaceholderAPI] failed to load class files of expansions
java.util.concurrent.CompletionException: java.lang.UnsupportedClassVersionError: META-INF/versions/9/module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_181]
Caused by: java.lang.UnsupportedClassVersionError: META-INF/versions/9/module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_181]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_181]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_181]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:63) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$4(LocalExpansionManager.java:319) ~[?:?]
        ... 6 more



After the papi version of 2.10.9 is overloaded, report this paragraph directly, and that's all I can provide

**Comment by Kqliber** [comment]
Hey, please try the jar linked below and this should fix the error for java 8 users. Once you can confirm this jar works too I will upload it to the ecloud.

For future reference, you are getting this because you are on an outdated java version, java 11 is now LTS and PaperMC will be dropping support for anything below java 11 when mc 1.17 is released.
[Expansion-RNG file](https://github.com/Kqliber/Expansion-RNG/files/6135358/rng.zip)

**Comment by 157946a** [comment]
After downloading the test you gave me separately, all three variables are normal and no errors are reported.

**Comment by Kqliber** [comment]
you can input decimals, but the outcome will always be an integer
